# Generated by Django 3.2 on 2023-01-21 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230121_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10, message='Рейтинг не должен быть выше 10'), django.core.validators.MinValueValidator(1, message='Рейтинг не должен быть ниже 1')]),
        ),
    ]
